---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      imagePullSecrets:
      - name: registry-creds
      containers:
      - name: image
        image: localhost:30500/image-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "1.0.0"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: service-auth
              key: jwt-secret
        - name: IMAGE_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: service-auth
              key: image-service-token
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: s3-secret-key
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: s3-bucket
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: s3-region
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: storage-credentials
              key: s3-endpoint
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: redis-password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: postgres-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: postgres-host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: postgres-database
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: image-service
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-service-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: image-service-pdb
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: image-service